# Generated by Django 5.1.3 on 2025-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaylistTrack",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "playlist_track",
                "managed": False,
            },
        ),
    ]
