# Generated by Django 5.1.3 on 2025-04-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("artist_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "db_table": "artist",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("genre_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "db_table": "genre",
            },
        ),
        migrations.CreateModel(
            name="MediaType",
            fields=[
                ("media_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "db_table": "media_type",
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("playlist_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "db_table": "playlist",
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                ("album_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=160)),
                (
                    "artist",
                    models.ForeignKey(
                        db_column="artist_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.artist",
                    ),
                ),
            ],
            options={
                "db_table": "album",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                ("birth_date", models.DateTimeField(blank=True, null=True)),
                ("hire_date", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=70, null=True)),
                ("city", models.CharField(blank=True, max_length=40, null=True)),
                ("state", models.CharField(blank=True, max_length=40, null=True)),
                ("country", models.CharField(blank=True, max_length=40, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("phone", models.CharField(blank=True, max_length=24, null=True)),
                ("fax", models.CharField(blank=True, max_length=24, null=True)),
                ("email", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        db_column="reports_to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=20)),
                ("company", models.CharField(blank=True, max_length=80, null=True)),
                ("address", models.CharField(blank=True, max_length=70, null=True)),
                ("city", models.CharField(blank=True, max_length=40, null=True)),
                ("state", models.CharField(blank=True, max_length=40, null=True)),
                ("country", models.CharField(blank=True, max_length=40, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("phone", models.CharField(blank=True, max_length=24, null=True)),
                ("fax", models.CharField(blank=True, max_length=24, null=True)),
                ("email", models.CharField(max_length=60)),
                (
                    "support_rep",
                    models.ForeignKey(
                        blank=True,
                        db_column="support_rep_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.employee",
                    ),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("invoice_date", models.DateTimeField()),
                (
                    "billing_address",
                    models.CharField(blank=True, max_length=70, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "billing_state",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "billing_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.customer",
                    ),
                ),
            ],
            options={
                "db_table": "invoice",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("track_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("composer", models.CharField(blank=True, max_length=220, null=True)),
                ("milliseconds", models.IntegerField()),
                ("bytes", models.IntegerField(blank=True, null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        db_column="album_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.album",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        db_column="genre_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.genre",
                    ),
                ),
                (
                    "media_type",
                    models.ForeignKey(
                        db_column="media_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.mediatype",
                    ),
                ),
            ],
            options={
                "db_table": "track",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "invoice_line_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        db_column="invoice_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.invoice",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        db_column="track_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.track",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line",
            },
        ),
    ]
