# Generated by Django 5.1.3 on 2025-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_artist_genre_mediatype_playlist_album_employee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="tracks_count_per_genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(blank=True, max_length=20, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tracks_count_per_genre",
                "managed": False,
            },
        ),
    ]
