# Generated by Django 5.1.3 on 2025-05-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_deletedcustomerlog_delete_tracks_count_per_genre_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deletedcustomerlog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="invoiceline",
            options={},
        ),
        migrations.AlterModelOptions(
            name="playlisttrack",
            options={},
        ),
    ]
