# Generated by Django 5.1.3 on 2025-05-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_alter_deletedcustomerlog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"managed": False},
        ),
    ]
