# Generated by Django 5.1.3 on 2025-06-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0007_alter_price_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="album",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediatype",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
