# Generated by Django 5.1.3 on 2025-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0008_remove_track_unit_price_album_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "personalinfo",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="fax",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="state",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="city",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="country",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="fax",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="state",
        ),
    ]
